### ISSUE TITLE
Expand CoC to Include Language Regarding Illegal/Grey Area Behavior

### ISSUE THREAD

**Issue by robertmaxrees** [jquery/irc.jquery.org#16]
It might be a good idea to expand the CoC to include language that covers cases like us assisting with things like piracy/warez, academic dishonesty (i.e. cheating), and other similar behavior, even if it's possible that the actions aren't necessarily "wrong", but they aren't totally "right", either.

We include a provision that says to listen to mods and follow the CoC in spirit, but I don't see anything that explicitly prohibits these kinds of behaviors.

Before I start getting into gear here, I'm curious to see what others have to say.  Am I missing any topics that might warrant explicit mention?  Should we not worry about this at all?

**Comment by arthurvr** [comment]
> Before I start getting into gear here, I'm curious to see what others have to say. Am I missing any topics that might warrant explicit mention? Should we not worry about this at all?

I'm +1 on a brief note.

**Comment by Krinkle** [comment]
Closing as the jQuery Foundation CoC has been superseded by OpenJS Foundation's one.

<https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md>

Future issues may be brought up there via the CPC issue tracker.
