### ISSUE TITLE
IRC logging has stopped

### ISSUE THREAD

**Issue by taplar** [jquery/irc.jquery.org#23]
http://irc.jquery.org/%23jquery/

It looks like the last log for #jquery is back on the 28th of last month.

**Comment by mgol** [comment]
Thanks for the report. This is most likely because we had to enable forced user authentication on jQuery-related channels because of recent heavy spamming. We'll need to find out where is the archiving code located and make sure it authenticates itself.

**Comment by taplar** [comment]
Any updates on this?

**Comment by mgol** [comment]
No updates yet, sorry. Our infrastructure team has people shortage so issues that don't break the world are not a priority. I'll try to look into that but I can't promise a quick solution.

**Comment by taplar** [comment]
The logs appear to be active once more.  Thank you to whom ever resolved this issue.
