### ISSUE TITLE
Migrate to Libera?

### ISSUE THREAD

**Issue by robertmaxrees** [jquery/irc.jquery.org#24]
Given current events happening within Freenode, is there interest in migrating any channels over to Libera or another network/platform?

**Comment by mgol** [comment]
I'm not familiar with what happens with Freenode. That said, IRC is almost not used nowadays by any jQuery project...

**Comment by robertmaxrees** [comment]
can see information here:
https://boingboing.net/2021/05/19/freenode-irc-staff-quit-after-new-owner-seizes-control.html

we still have a small trickle of folks looking for support in the main #jquery channel, one of whom asked today if we've registered over there or not.

**Comment by timmywil** [comment]
If the situation is the same, we're interested in migrating to Libera and posting a link on the site. However, the active jQuery team members will likely continue to use gitter and slack.

**Comment by robertmaxrees** [comment]
it definitely is.

it looks like all channels and user accounts were effectively "reset" on freenode.  the irc crew is slowly dwindling.  guessing most of the remaining people are coming in because their client automatically joins for them on startup.

let me know if there's anything i can do to help.  thanks!

**Comment by mgol** [comment]
@robertmaxrees as Timmy mentioned, we're not that involved with IRC nowadays so if you could tell us exactly what we need to do, that'd help a lot. Thanks!

**Comment by crabbedhaloablution** [comment]
Follow the instructions at: https://libera.chat/chanreg
The person who does this should have a nickname registered on Libera Chat and some way of verifying that they are with the project. This may entail committing a 'cookie' text string to the repo to verify commit access.

**Comment by mgol** [comment]
Looking at https://libera.chat/chanreg, it seems I need the jQuery project created first, unless one is already registered? I also see that the `#jquery` channel already exists on Libera, who is the owner?

I've created an account for myself on Libera and registered `mgol` as a nick.

**Comment by crabbedhaloablution** [comment]
There's likely no owner of #jquery rigth now. It isn't registered with chanserv at least. Getting the project registered will give you a namespace and the ability to take over ops automatically in #jquery without justifying it on case-by-case basis to the staff.

**Comment by mgol** [comment]
I filled in the form to register the jQuery project owning `#jquery` & `#jquery-*` and I can already manage `#jquery`. Now we need to update docs, bots, etc. and wait for the project registration to be processed.

**Comment by Krinkle** [comment]
Marking as stale for now as I'm not sure to what extent we want to centrally document where and which of the former jQuery Foundation-hosted projects have their IRC channels. We haven't hosted a bouncer for a while, and the logbot was running on life support for the past 4 years on a VM with an end-of-life OS and setup scripts that didn't cleanly provision on a new instance.

Of course individual projects do have their own websites where support channels are documented, so I would encourage those to update those accordingly. E.g. to point to Libera, Matrix, or whichever the official support channel(s) are.

**Comment by Krinkle** [comment]
In late 2021, we did indeed set up a `#jquery` channel on Libera Chat IRC. We've also been on Gitter for a long time, which [is now fully integrated](https://blog.gitter.im/2023/02/13/gitter-has-fully-migrated-to-matrix/) with Matrix. 

Latest links at <http://irc.jquery.org/>
