### ISSUE TITLE
Add IRC bot page

### ISSUE THREAD

**Issue by ajpiano** [jquery/irc.jquery.org#3]
Explain bot features, commands, etc.

**Comment by rickycodes** [comment]
@ajpiano can I get unassigned from this? b-ot is d-ead

**Comment by miketaylr** [comment]
![](http://imagesmtv-a.akamaihd.net/uri/mgid:file:http:shared:mtv.com/news/wp-content/uploads/2015/06/gooniesdie-1433528444.gif)
