### ISSUE TITLE
Disable search?

### ISSUE THREAD

**Issue by ajpiano** [jquery/irc.jquery.org#4]
Search probably gives the distinct impression that it will allow searching the IRC logs, which, for the forseeable future, it won't. Should we get rid of the search box on this site?

**Comment by arthurvr** [comment]
> Should we get rid of the search box on this site?

Yup, sounds good :+1:. Is there a good way to disable search using the wordpress setup? [There's this workaround in the `sizzlejs.com` theme ](https://github.com/jquery/jquery-wp-content/blob/50c5caea6c8330e670860252ea1eb7673d668269/themes/sizzlejs.com/searchform.php)but I wonder if there's a better way.

**Comment by Krinkle** [comment]
Fixed, by pointing to GitHub Search for the new static version of the archive.
