### ISSUE TITLE
Create a code of conduct for #jquery

### ISSUE THREAD

**Issue by gnarf** [jquery/irc.jquery.org#8]
Some good points in here we could probably steal from @isaacs and #Node.js

http://blog.izs.me/post/30036893703/policy-on-trolling

**Comment by arthurvr** [comment]
@robertmaxrees Do you have any thoughts on this?

**Comment by gnarf** [comment]
cc @ajpiano @RedWolves

**Comment by robertmaxrees** [comment]
I can (hopefully) try to spend some time soon to put together something that borrows from the link @gnarf provided while also reflecting on some of the values we've developed in the channel as of late.  Might be worthwhile to also revisit some of what we have on http://irc.jquery.org/irc-help/ to make sure we're putting forward a clear, consistent message overall.

Just some thoughts.

**Comment by ajpiano** [comment]
I haven't been nearly as attentive to #jquery as I was in years past but am definitely in favor of something like this. I would love to hear about/see what you'd put together @robertmaxrees

**Comment by RedWolves** [comment]
Can we add this to the topics of our channels?

**Comment by RedWolves** [comment]
Can we add a link to the CoC  in the topics of our channels?

**Comment by arthurvr** [comment]
> Can we add a link to the CoC in the topics of our channels?

For `#jquery` that seems like a good idea. I don't think it's needed in dev channels, we know the rules :)

**Comment by RedWolves** [comment]
It's still an open channel that gets random people dropping by... I think it's important to list it in all channels.

**Comment by gnarf** [comment]
We should probably add a link from all jquery channels.
