### ISSUE TITLE
Document how to use IRC clients

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/irc.jquery.org#9]
http://irc.jquery.org/irc-help/ suggests specific IRC clients, but doesn't explain how to connect to freenode and the individual channels once installed.

**Comment by arthurvr** [comment]
Are there any good resources/posts about this we could link to instead? I think a simple link to one would be enough. Documenting how to use IRC clients seems out of the scope of this site, isn't it?

**Comment by robertmaxrees** [comment]
We might want to either link directly to the different clients' help pages or (even better imo) simply tell people the server/channel and then maybe link into any relevant resources on the freenode website.  I feel like the material is already out there - if their client is giving them trouble, they should be able to figure out how to fix it.

**Comment by xfq** [comment]
Richard Esplin's [Getting Started with Freenode IRC](http://richard.esplins.org/siwi/2011/07/08/getting-started-freenode-irc/) is a helpful guide. Both [WPD](https://docs.webplatform.org/wiki/WPD:Editors_Guide/step_2_communicate_with_the_online_community/irc_clients) and [movethewebforward.org
](https://github.com/h5bp/movethewebforward/blob/311f214fbee85205a135433d4c5cec710c25162b/index.html#L128) link to this article.

Mozilla's [IRC introduction page](https://wiki.mozilla.org/IRC) also has many useful information for choosing/registering a nickname, joining channels, sending private messages, etc.

The Fedora Project has a great FAQ on how to use IRC: http://fedoraproject.org/wiki/Fedora_Channel_FAQ

[IRChelp.org](http://www.irchelp.org/) includes FAQs, primers, technical guides, plus many other useful things about IRC.

[IRC.org](http://www.irc.org/) offers technical and historical documents about IRC.

Freenode's FAQ: https://freenode.net/faq.shtml

[IRCBeginner.com](http://www.ircbeginner.com/) contains some documents and FAQs for the beginner, although it hasn't been updated for ~10 years.

**Comment by arthurvr** [comment]
Thanks for the links @xfq.
